### ISSUE TITLE
.py and .ipynb recognized as same file extension

### ISSUE THREAD

**Issue by martin-gc** [jsaulou/vscode-theme-by-language#17]
When a theme is set for .py or .ipynb it is applied to both, even though file extensions are different, am I doing something wrong?

**Comment by jsaulou** [comment]
Themes are stored by file types not extensions. That's why it behaves this way. You're not doing anything wrong. Both `py` and `ipynb` must be associated with python file type.
I can't think of a workaround right now unfortunately. I think to make this work, modifications would be required to associate by file extensions too.

**Comment by martin-gc** [comment]
Ok, thanks!
